export default {

	SETTINGS : 'SETTINGS',

	ERROR_SERVER         : 'ERROR_SERVER',
	ERROR_SCHEMA         : 'ERROR_SCHEMA',
	ERROR_PRECONDITION   : 'ERROR_PRECONDITION',
	ERROR_DATA           : 'ERROR_DATA',
	ERROR_TIMEOUT        : 'ERROR_TIMEOUT',	
	ERROR_AUTHENTICATION : 'ERROR_AUTHENTICATION',

	SESSION_TIMEOUT        : 'SESSION_TIMEOUT',
	SESSION_PASSWORD_INPUT : 'SESSION_PASSWORD_INPUT',

	BUTTON_SUBMIT : 'BUTTON_SUBMIT',
	BUTTON_CANCEL : 'BUTTON_CANCEL',
	BUTTON_DELETE : 'BUTTON_DELETE',

	DIALOG_OK     : 'DIALOG_OK',
	DIALOG_CANCEL : 'DIALOG_CANCEL',
	DIALOG_SUBMIT : 'DIALOG_SUBMIT',
	DIALOG_APPLY  : 'DIALOG_APPLY',
	DIALOG_RESET  : 'DIALOG_RESET',
	DIALOG_SEARCH : 'DIALOG_SEARCH',
	DIALOG_EDIT   : 'DIALOG_EDIT',
	DIALOG_ALERT  : 'DIALOG_ALERT',	
	DIALOG_ERROR  : 'DIALOG_ERROR',

	ACTION_CONFIRM : 'ACTION_CONFIRM',
	ACTION_CANCEL  : 'ACTION_CANCEL',
	ACTION_SUCCESS : 'ACTION_SUCCESS',
	ACTION_ERROR   : 'ACTION_ERROR',

	TASKS             : 'TASKS',
	TASK_REFRESH      : 'TASK_REFRESH',
	TASK_OPTIONS      : 'TASK_OPTIONS',
	TASK_ASSIGN       : 'TASK_ASSIGN',
	TASK_ASCENDING    : 'TASK_ASCENDING',
	TASK_DESCENDING   : 'TASK_DESCENDING',
	TASK_ERROR        : 'TASK_ERROR',
	TASK_RESOURCE     : 'TASK_RESOURCE',
	TASK_NEXT         : 'TASK_NEXT',
	TASK_ASSIGN_ERROR : 'TASK_ASSIGN_ERROR',
	TASK_INVALID      : 'TASK_INVALID',
	TASK_FILTER       : 'TASK_FILTER',
	TASK_SORT         : 'TASK_SORT',
	TASK_GROUP        : 'TASK_GROUP',

	EVENTS                 : 'EVENTS',
	EVENT_UPDATE_AVAILABLE : 'EVENT_UPDATE_AVAILABLE',
	EVENT_ADD              : 'EVENT_ADD',
	EVENT_UPDATE           : 'EVENT_UPDATE',
	EVENT_REMOVE           : 'EVENT_REMOVE',

	TOAST_ALERT            : 'TOAST_ALERT',
	TOAST_UPDATE           : 'TOAST_UPDATE',
	TOAST_UPDATE_AVAILABLE : 'TOAST_UPDATE_AVAILABLE',

	ACCOUNT_CHOOSE      : 'ACCOUNT_CHOOSE',
	ACCOUNT_LOGOUT_ALL  : 'ACCOUNT_LOGOUT_ALL',
	ACCOUNT_LOGOUT      : 'ACCOUNT_LOGOUT',
	ACCOUNT_CHANGE      : 'ACCOUNT_CHANGE',

	BOOKMARK       : 'BOOKMARK',
	BOOKMARKS      : 'BOOKMARKS',
	CLIPBOARD_COPY : 'CLIPBOARD_COPY',
	TSV_PARSE      : 'TSV_PARSE',
	CSV_PARSE      : 'CSV_PARSE',
	YAML_PARSE     : 'YAML_PARSE',
	DATA_PARSE     : 'DATA_PARSE',

	HELP      : 'HELP',
	API       : 'API',
	HELP_KEYS : 'HELP_KEYS',

	SIDEBAR_ACTION_TOGGLE : 'SIDEBAR_ACTION_TOGGLE',

  OPERATOR_LIKE                  : 'OPERATOR_LIKE',
  OPERATOR_EQUAL                 : 'OPERATOR_EQUAL',
  OPERATOR_NOT_EQUAL             : 'OPERATOR_NOT_EQUAL',
  OPERATOR_GREATER_THAN          : 'OPERATOR_GREATER_THAN',
  OPERATOR_GREATER_THAN_OR_EQUAL : 'OPERATOR_GREATER_THAN_OR_EQUAL',
  OPERATOR_LESS_THAN             : 'OPERATOR_LESS_THAN',
  OPERATOR_LESS_THAN_OR_EQUAL    : 'OPERATOR_LESS_THAN_OR_EQUAL',

  INPUT_REQUIRED   : 'INPUT_REQUIRED',
	INPUT_EMAIL      : 'INPUT_EMAIL',
	INPUT_MIN_LENGTH : 'INPUT_MIN_LENGTH',
	INPUT_MAX_LENGTH : 'INPUT_MAX_LENGTH',

	KEYBOARD_ENTER       : 'KEYBOARD_ENTER',
	KEYBOARD_ESCAPE      : 'KEYBOARD_ESCAPE',
	KEYBOARD_TAB         : 'KEYBOARD_TAB',
	KEYBOARD_FULL_SCREEN : 'KEYBOARD_FULL_SCREEN',
	KEYBOARD_SPOTLIGHT   : 'KEYBOARD_SPOTLIGHT',

};